stages:
  - test
  - build
  - deploy

linit-and-test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk add make
  script:
    - make check
    - make test

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
