stages:
  - test
  - build
  - deploy

variables:
  IMAGES_REPO: $REGISTRY_USER/$PROJECT

test-with-linters:
  stage: test
  image: docker:27.0
  services:
    - docker:27-dind
  before_script:
    - apk update && apk add make
    - make build
  script:
    - make check
    - make test

build:
  stage: build
  image: docker:27.0
  services:
    - docker:27-dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGES_REPO:backend backend
    - docker build -t $IMAGES_REPO:frontend frontend
    - docker push $IMAGES_REPO:backend
    - docker push $IMAGES_REPO:frontend
  after_script:
    - docker logout

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_ROOT "
      cd $PROJECT/ &&
      docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      make down env=prod &&
      docker images -q IMAGES_REPO | xargs docker rmi &&
      make run env=prod"
