stages:
  - test
  - build
  - deploy

test-with-linters:
  stage: test
  image: docker:27.0
  services:
    - docker:27-dind
  before_script:
    - apk update && apk add make
    - make build
  script:
    - make check
    - make test

build:
  stage: build
  image: docker:27.0
  services:
    - docker:27-dind
  variables:
    IMAGE_REPO: $REGISTRY_USER/$REGISTRY_REPO
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_REPO:backend backend
    - docker build -t $IMAGE_REPO:frontend frontend
    - docker push $IMAGE_REPO:backend
    - docker push $IMAGE_REPO:frontend
  after_script:
    - docker logout

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
