stages:
  - prepare
  - test
  - build
  - deploy

image: docker:latest
services:
  - docker:dind

prepare-job:
  stage: prepare
  script:
    - apt-get update && apt-get install -y make
  artifacts:
    paths:
      - /usr/bin/make

unit-test-job:
  stage: test
  dependencies:
    - prepare-job
  script:
    - make test

lint-test-job:
  stage: test
  dependencies:
    - prepare-job
  script:
    - make check

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
