stages:
  - test
  - build
  - deploy

test-with-linters:
  stage: test
  image: docker:27.0
  services:
    - docker:27-dind
  before_script:
    - apk update && apk add make
    - make build
  script:
    - make check
    - make test

build:
  stage: build
  image: docker:27.0
  services:
    - docker:27-dind
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  when: manual
