services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .envs/.flask
      - .envs/.postgres
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:15.3-alpine
    env_file:
      - .envs/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: sh -c "pg_isready -U postgres"
      interval: 3s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "82:80"
    depends_on:
      web:
        condition: service_started

volumes:
  postgres_data:
