services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs/gunicorn:/backend/logs/gunicorn
    env_file:
      - .envs/.flask

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "82:80"
    depends_on:
      web:
        condition: service_started
