"""Empty message.

Revision ID: 382957c71e3e
Revises: 9461cb918c36
Create Date: 2024-04-17 22:09:11.667411
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "382957c71e3e"
down_revision = "9461cb918c36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_column("days_participation_length")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "days_participation_length",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
