"""empty message

Revision ID: 44dc79f271e6
Revises: b684c76f1635
Create Date: 2024-04-19 19:13:42.233065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44dc79f271e6"
down_revision = "b684c76f1635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_participants",
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_participants")
    op.drop_table("events")
    # ### end Alembic commands ###
