"""Empty message.

Revision ID: 5d8e53ebcf24
Revises: 382957c71e3e
Create Date: 2024-04-17 23:12:00.724903
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5d8e53ebcf24"
down_revision = "382957c71e3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.alter_column(
            "meal_preference",
            existing_type=postgresql.ENUM(
                "CARNIVOROUS", "VEGETARIAN", name="mealspreference"
            ),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.alter_column(
            "meal_preference",
            existing_type=postgresql.ENUM(
                "CARNIVOROUS", "VEGETARIAN", name="mealspreference"
            ),
            nullable=False,
        )

    # ### end Alembic commands ###
