"""Empty message.

Revision ID: 9461cb918c36
Revises:
Create Date: 2024-04-17 15:27:22.284398
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9461cb918c36"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("BREAKFAST", "DINNER", "SUPPER", name="mealtype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.execute(sa.text("INSERT INTO meals (type) VALUES ('BREAKFAST')"))
    op.execute(sa.text("INSERT INTO meals (type) VALUES ('DINNER')"))
    op.execute(sa.text("INSERT INTO meals (type) VALUES ('SUPPER')"))
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("is_host", sa.Boolean(), nullable=True),
        sa.Column("days_participation_length", sa.Integer(), nullable=False),
        sa.Column(
            "meal_preference",
            sa.Enum("CARNIVOROUS", "VEGETARIAN", name="mealspreference"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participant_meals",
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("meal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("participant_meals")
    op.drop_table("participants")
    op.drop_table("meals")
    # ### end Alembic commands ###
