"""empty message

Revision ID: adfeb9df2e22
Revises: 44dc79f271e6
Create Date: 2024-04-19 22:54:56.588986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adfeb9df2e22"
down_revision = "44dc79f271e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
